# lib/local.nix — Impure-aware loader for the gitignored `.local/` settings layer
#
# WHY THIS EXISTS (empirically verified, see AGENTS.md "Local Settings Layer"):
#   * `.local/` is gitignored. Inside a `git+file:` flake, relative reads like
#     `builtins.pathExists ./.local/...` silently evaluate to `false` because
#     untracked files are excluded from the Nix store evaluation copy.
#   * The `path:` scheme is NOT a safe workaround: it copies `.git/` into the
#     store and hard-fails on `.git/fsmonitor--daemon.ipc` (this repo enables
#     `core.fsmonitor`). With `.local` as an out-of-tree symlink it still
#     resolves to MISSING under pure evaluation.
#   * The only pattern that works for BOTH a plain gitignored directory and a
#     `.local -> ~/dotfiles-private` symlink is an absolute-path read under
#     `--impure`. `scripts/bin/rebuild` passes the flag and exports
#     `DOTFILES_LOCAL` explicitly (sudo may rewrite $HOME).
#
# PURITY CONTRACT:
#   Under pure evaluation (`nix flake check`, CI, cold clones) `getEnv`
#   returns "" and this loader degrades to empty settings — every optional
#   set stays disabled and evaluation succeeds. Nothing here throws.
#
# SETTINGS SCHEMA (all keys optional):
#   .local/identity.nix           { name = "..."; email = "..."; }
#   .local/settings.nix           { ai.enable = bool;
#                                   casks = [ ... ]; nixPackages = [ ... ];
#                                   masApps = { Name = 123; }; }
#   .local/apps.nix               same shape, written by `dot apps` — never
#                                 hand-edited; concatenated with settings.nix
#   .local/hosts/                 reserved for the private flake (never
#                                 auto-imported here, to avoid double imports)
#
# There is exactly ONE place to declare an application: the `casks` /
# `nixPackages` / `masApps` lists above. An earlier design split them across
# per-category `browsers/choices.nix` and `editors/choices.nix` files feeding
# five `dotfiles.apps.<set>` modules whose mkOption defaults hardcoded the
# upstream author's own apps. Those lists CONCATENATED rather than replaced, so
# an adopter could add their browser but never remove the author's — which is
# how a "de-opinionated" framework still installed someone else's apps.

let
  # Resolution order: explicit override → <repo>/.local
  #
  # ~/dotfiles-private is deliberately NOT a candidate (ADR-007).
  # `scripts/bin/setup-private-host` creates that directory containing only
  # flake.nix/flake.lock/hosts/, with no settings files at all. Treating it as
  # a settings layer flipped `exists` to true with an EMPTY cask list, which
  # made Homebrew cleanup default to "uninstall" and wipe every cask on the
  # machine. The supported way to back .local/ with the private repo is the
  # symlink `install.sh` creates (`.local -> ~/dotfiles-private`), which
  # resolves through the candidate below and is unaffected by this change.
  envLocal = builtins.getEnv "DOTFILES_LOCAL";
  home = builtins.getEnv "HOME";

  candidates =
    (if envLocal != "" then [ envLocal ] else [ ])
    ++ (if home != "" then [ "${home}/dotfiles/.local" ] else [ ]);

  # Convert an absolute path string to a path value (works under --impure)
  toAbsPath = s: /. + s;

  # A directory is a settings layer only if it carries at least one recognized
  # settings file. A bare directory must never flip `exists` — presence is not
  # consent (ADR-007). Keep this list in sync with `has_settings_layer()` in
  # scripts/bin/rebuild.
  settingsFiles = [
    "settings.nix"
    "identity.nix"
    "apps.nix" # generated by `dot apps` — never hand-edited
  ];

  hasSettings = d:
    builtins.any (f: builtins.pathExists (toAbsPath "${d}/${f}")) settingsFiles;

  # First candidate that exists AND carries content. Note the difference from a
  # plain existence check: an empty ./.local no longer shadows a populated
  # $DOTFILES_LOCAL.
  firstWithSettings = paths:
    if paths == [ ] then null
    else if hasSettings (builtins.head paths)
    then builtins.head paths
    else firstWithSettings (builtins.tail paths);

  dir = firstWithSettings candidates;

  importIfPresent = rel:
    if dir != null && builtins.pathExists (toAbsPath "${dir}/${rel}")
    then import (toAbsPath "${dir}/${rel}")
    else { };

  settings = importIfPresent "settings.nix";
  appsFile = importIfPresent "apps.nix";
  identityRaw = importIfPresent "identity.nix";
in
{
  # True only when a settings layer WITH CONTENT was found (false in pure eval).
  # This flag gates nothing behavioural — it exists so tooling can warn when no
  # layer is present. Never use it to infer consent for a destructive or
  # opinionated default; read an explicit accessor below instead (ADR-007).
  exists = dir != null;
  inherit dir settings;

  identity = if identityRaw == { } then null else identityRaw;

  # The complete declared application set for this machine. Hand-edited
  # settings.nix plus whatever `dot apps` has written to apps.nix — nothing
  # else. If an app is not named here it is not installed, whoever wrote the
  # framework.
  casks = (settings.casks or [ ]) ++ (appsFile.casks or [ ]);
  nixPackages = (settings.nixPackages or [ ]) ++ (appsFile.nixPackages or [ ]);
  # Mac App Store apps, as { AppName = <numeric App Store ID>; }. An empty set
  # means the `mas` CLI is not installed either — see nix/modules/mas.nix.
  masApps = (settings.masApps or { }) // (appsFile.masApps or { });

  # Toggle helpers with safe fallbacks
  aiEnabled = settings.ai.enable or false;

  # Explicit opt-ins. `null` means "not specified" — the consuming module
  # supplies its own (non-destructive, non-opinionated) default. These exist so
  # no module has to infer intent from mere directory presence (ADR-007).
  homebrewCleanup = settings.homebrew.cleanup or null;
  macosDefaults = settings.system.macosDefaults.enable or null;
  homeProfile = settings.home.exampleProfile.enable or null;
}
